name: Bug Report
description: Report a bug or issue with SnapCode
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., Windows 10, macOS 12.1, Ubuntu 20.04
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g., Chrome 91, Firefox 89, Safari 14
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: e.g., Desktop, Mobile, Tablet

  - type: input
    id: version
    attributes:
      label: SnapCode Version
      placeholder: e.g., 1.3.0

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar issues and confirmed this is not a duplicate
          required: true
        - label: I have tested this on the latest version of SnapCode
          required: true
        - label: I have provided all the information requested above
          required: true